previewsEnabled: true
previewsExpireAfterDays: 1
services:
  - type: web
    env: node
    plan: free
    name: render-preview-test
    buildCommand: npm ci && npm run db:migrate:latest
    startCommand: npm start
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: expert-preview-test
          property: connectionString
      - fromGroup: BACKEND_ENVIRONMENTS
      - fromGroup: BACKEND_SECRETS
databases:
  - name: expert-preview-test
envVarGroups:
  - name: BACKEND_ENVIRONMENTS
    envVars:
      - key: ONLY_PREVIEW
        sync: false
        previewValue: this-is-variable-from-preview
      - key: TEST_VARIABLE_WITH_NO_SYNC
        sync: false
å