previewsEnabled: true
previewsExpireAfterDays: 1
services:
  - type: web
    env: node
    name: render-preview-test
    buildCommand: npm ci && npm run db:migrate:latest
    startCommand: RUN_EVNIRONMENT="${HOSTNAME}onrender" npm start
    envVars:
      - key: HOSTNAME
        fromService:
          type: web
          name: render-preview-test
          property: host
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: expert-preview-test
          property: connectionString
      - fromGroup: BACKEND_ENVIRONMENTS
databases:
  - name: expert-preview-test
envVarGroups:
  - name: BACKEND_ENVIRONMENTS
    envVars:
      - key: TEST_ENV_VARIABLE
        sync: false
        previewValue: this-is-variable-from-preview
      - key: NEW_TEST_ENV
        value: newly-added-env-variable